### ISSUE TITLE
Installation difficulty on Windows starting v1.6.1

### ISSUE THREAD

**Issue by elrandira** [Kijewski/pyjson5#31]
Hi,

since the delivery of 1.6.1, I am facing issue to install pyjson5 on Windows. I have the following that don't appear with 1.6.0 ( and didn't with 1.6.0.post1).

Installing the following didn't solve the issue:
- Microsoft Visual C++ 2015-2019 Redistributable (x64) v14.29.30139.0
- Microsoft Visual C++ 2015-2019 Redistributable (x86) v14.29.30139.0
- Visual Studio Build Tool 2019 v16.11.9

`
C:\>pip install -U pyjson5
Requirement already satisfied: pyjson5 in c:\users\lpinson\appdata\local\programs\python\python39\lib\site-packages (1.6.0)
Collecting pyjson5
  Using cached pyjson5-1.6.1.tar.gz (231 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pyjson5
  Building wheel for pyjson5 (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyjson5 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [76 lines of output]
      running bdist_wheel
      running build
      running build_py
      running egg_info
      writing src\pyjson5.egg-info\PKG-INFO
      writing dependency_links to src\pyjson5.egg-info\dependency_links.txt
      writing top-level names to src\pyjson5.egg-info\top_level.txt
      reading manifest file 'src\pyjson5.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'requires.txt'
      adding license file 'LICENSE'
      running build_ext
      skipping 'pyjson5.cpp' Cython extension (up-to-date)
      building 'pyjson5.pyjson5' extension
      Traceback (most recent call last):
        File "C:\Users\lpinson\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\lpinson\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\lpinson\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\build_meta.py", line 229, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\build_meta.py", line 214, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\build_meta.py", line 157, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 10, in <module>
          setup(
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 79, in run
          _build_ext.run(self)
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
          _build_ext.build_ext.run(self)
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
          self.build_extensions()
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
          _build_ext.build_ext.build_extensions(self)
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 528, in build_extension
          objects = self.compiler.compile(sources,
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 327, in compile
          self.initialize()
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
        File "C:\Users\lpinson\AppData\Local\Temp\pip-build-env-cm_jlz5o\overlay\Lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      setuptools._distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyjson5
Failed to build pyjson5
ERROR: Could not build wheels for pyjson5, which is required to install pyproject.toml-based projects
`

**Comment by elrandira** [comment]
as it was suggested in the issue above, installing the following makes further progress: 
> The magic checkbox seems to be:
> "[ ] MSVC v140 - VS 2015 C++ build tools (v14.00)"

Unfortunately, if I understand the error message, the issue is now the compilation option

> C:\>pip install -U pyjson5
Requirement already satisfied: pyjson5 in c:\users\lpinson\appdata\local\programs\python\python39\lib\site-packages (1.6.0)
Collecting pyjson5
  Using cached pyjson5-1.6.1.tar.gz (231 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pyjson5
  Building wheel for pyjson5 (pyproject.toml) ... error
  error: subprocess-exited-with-error

>   × Building wheel for pyjson5 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      running bdist_wheel
      running build
      running build_py
      running egg_info
      writing src\pyjson5.egg-info\PKG-INFO
      writing dependency_links to src\pyjson5.egg-info\dependency_links.txt
      writing top-level names to src\pyjson5.egg-info\top_level.txt
      reading manifest file 'src\pyjson5.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'requires.txt'
      adding license file 'LICENSE'
      running build_ext
      skipping 'pyjson5.cpp' Cython extension (up-to-date)
      building 'pyjson5.pyjson5' extension
      Command line warning D9002: ignoring unknown option '-std=c++11' 
      Command line warning D9002: ignoring unknown option '-O3' 
      Command line warning D9002: ignoring unknown option '-fPIC' 
      Command line warning D9002: ignoring unknown option '-ggdb1'
      Command line warning D9002: ignoring unknown option '-pipe' 
      Command line warning D9002: ignoring unknown option '-fomit-frame-pointer' 
      Command line warning D9002: ignoring unknown option '-fstack-protector-strong'
      pyjson5.cpp
      c:\users\lpinson\appdata\local\programs\python\python39\include\pyconfig.h(200): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory 
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2
      [end of output]

>   note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyjson5
Failed to build pyjson5
ERROR: Could not build wheels for pyjson5, which is required to install pyproject.toml-based projects


Note: some errors messages were translated from French to English

**Comment by Kijewski** [comment]
Thank you for informing me! I forgot to upload the pre-compiled wheels for Windows. Now it should work out-of-the-box, again.

**Comment by elrandira** [comment]
Install passed, case close. Thank you :)

And a big thanks for the implementing JSON5 in Python as well 🥇
